# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: before install
        run: |
          $CONDA/bin/conda info
          $CONDA/bin/conda list
          $CONDA/bin/conda config --add channels conda-forge
          $CONDA/bin/conda install obspy fortran-compiler pandas pytest-cov sphinx
          pip install sphinx_rtd_theme
          $CONDA/bin/conda list

      - name: install
        run: pip install -e .

      - name: docs
        run: |
          cd docs
          make html
          touch _build/html/.nojekyll
          cd ..

      - name: tests
        run: |
          mkdir empty
          cd empty
          pytest -v --cov=pyraysum ../pyraysum/tests/
          bash <(curl -s https://codecov.io/bash)

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_build/html # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch